// Type declarations for auto-generated modules
declare module '#graphql-operations' {
  export * from '#build/graphql-operations'
}

declare module '#build/graphql-operations' {
  // These types are auto-generated by nuxt-graphql-middleware
  export interface NodeByUriQueryVariables {
    uri?: string
  }

  export interface PostsQueryVariables {
    first?: number
    after?: string
  }

  // Fragment types
  export interface MenuItemFragment {
    id?: string
    label?: string
    url?: string
  }

  export interface PostFragment {
    id?: string
    title?: string
    content?: string
    slug?: string
    uri?: string
    date?: string
    excerpt?: string
    contentTypeName?: string
    categories?: {
      nodes?: Array<{ name?: string }>
    }
    featuredImage?: {
      node?: {
        sourceUrl?: string
        altText?: string
      }
    }
  }

  export interface PageFragment {
    id?: string
    title?: string
    content?: string
    slug?: string
    uri?: string
    date?: string
    contentTypeName?: string
    featuredImage?: {
      node?: {
        sourceUrl?: string
        altText?: string
      }
    }
  }

  export interface NodeWithContentEditorFragment {
    id?: string
    content?: string
  }

  export interface NodeWithEditorBlocksFragment {
    id?: string
    editorBlocks?: unknown[]
  }

  export interface NodeWithFeaturedImage {
    id?: string
    featuredImage?: {
      node?: {
        sourceUrl?: string
      }
    }
  }

  // Add more as needed by the actual GraphQL schema
  export type Maybe<T> = T | null
}

declare module '#wpnuxt/blocks' {
  // Placeholder for blocks module types
  export const CoreButton: unknown
  export const BlockRenderer: unknown
}
