import { z } from 'zod'
import { executeGraphQL, CONTENT_TYPES_QUERY, SITE_SETTINGS_QUERY } from '../../utils/graphql'

interface ContentType {
  name: string
  graphqlSingleName: string
  graphqlPluralName: string
  hierarchical: boolean
  hasArchive: boolean | null
}

interface SiteSettings {
  readingSettings: {
    showOnFront: string
    pageOnFront: number
    pageForPosts: number
  }
}

type DisplayStyle = 'grid' | 'list' | 'detailed'

function generateListPage(
  ct: ContentType,
  displayStyle: DisplayStyle = 'grid',
  customRoute?: string
): { filename: string, content: string } {
  const plural = ct.graphqlPluralName
  const singular = ct.graphqlSingleName
  const pluralCapitalized = plural.charAt(0).toUpperCase() + plural.slice(1)

  // Generate template based on display style
  const templateContent = {
    grid: `    <div v-else-if="${plural}" class="${plural}-grid">
      <article
        v-for="${singular} in ${plural}"
        :key="${singular}.id"
        class="${singular}-card"
      >
        <NuxtLink :to="${singular}.uri">
          <img
            v-if="${singular}.featuredImage"
            :src="${singular}.featuredImage.node.sourceUrl"
            :alt="${singular}.featuredImage.node.altText || ${singular}.title"
            class="card-image"
          />
          <div class="card-content">
            <h2>{{ ${singular}.title }}</h2>
            <p v-if="${singular}.excerpt" v-html="${singular}.excerpt" />
          </div>
        </NuxtLink>
      </article>
    </div>`,
    list: `    <ul v-else-if="${plural}" class="${plural}-list">
      <li v-for="${singular} in ${plural}" :key="${singular}.id" class="${singular}-item">
        <NuxtLink :to="${singular}.uri">
          {{ ${singular}.title }}
        </NuxtLink>
      </li>
    </ul>`,
    detailed: `    <div v-else-if="${plural}" class="${plural}-detailed">
      <article
        v-for="${singular} in ${plural}"
        :key="${singular}.id"
        class="${singular}-row"
      >
        <img
          v-if="${singular}.featuredImage"
          :src="${singular}.featuredImage.node.sourceUrl"
          :alt="${singular}.featuredImage.node.altText || ${singular}.title"
          class="row-image"
        />
        <div class="row-content">
          <NuxtLink :to="${singular}.uri">
            <h2>{{ ${singular}.title }}</h2>
          </NuxtLink>
          <p v-if="${singular}.excerpt" v-html="${singular}.excerpt" />
          <time v-if="${singular}.date" :datetime="${singular}.date">
            {{ new Date(${singular}.date).toLocaleDateString() }}
          </time>
        </div>
      </article>
    </div>`
  }

  const styleContent = {
    grid: `
.${plural}-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 2rem;
}

.${singular}-card {
  border: 1px solid #eee;
  border-radius: 8px;
  overflow: hidden;
  transition: box-shadow 0.2s;
}

.${singular}-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.${singular}-card a {
  text-decoration: none;
  color: inherit;
}

.card-image {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.card-content {
  padding: 1rem;
}

.card-content h2 {
  margin: 0 0 0.5rem;
  font-size: 1.25rem;
}

.card-content p {
  margin: 0;
  color: #666;
  font-size: 0.9rem;
}`,
    list: `
.${plural}-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.${singular}-item {
  padding: 0.75rem 0;
  border-bottom: 1px solid #eee;
}

.${singular}-item:last-child {
  border-bottom: none;
}

.${singular}-item a {
  text-decoration: none;
  color: inherit;
  font-size: 1.1rem;
}

.${singular}-item a:hover {
  color: #0066cc;
}`,
    detailed: `
.${plural}-detailed {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.${singular}-row {
  display: flex;
  gap: 1.5rem;
  padding-bottom: 2rem;
  border-bottom: 1px solid #eee;
}

.${singular}-row:last-child {
  border-bottom: none;
}

.row-image {
  width: 200px;
  height: 150px;
  object-fit: cover;
  border-radius: 8px;
  flex-shrink: 0;
}

.row-content {
  flex: 1;
}

.row-content h2 {
  margin: 0 0 0.5rem;
}

.row-content a {
  text-decoration: none;
  color: inherit;
}

.row-content a:hover h2 {
  color: #0066cc;
}

.row-content p {
  margin: 0 0 0.5rem;
  color: #666;
}

.row-content time {
  font-size: 0.85rem;
  color: #999;
}

@media (max-width: 600px) {
  .${singular}-row {
    flex-direction: column;
  }

  .row-image {
    width: 100%;
    height: 200px;
  }
}`
  }

  const content = `<script setup lang="ts">
/**
 * ${pluralCapitalized} Archive Page
 * Generated by WPNuxt MCP
 * Display style: ${displayStyle}
 */

// Fetch ${plural} with pagination
const { data: ${plural}, pending, error } = await use${pluralCapitalized}({
  first: 10
})

// SEO
useSeoMeta({
  title: '${pluralCapitalized}',
  description: 'Browse all ${plural}'
})
</script>

<template>
  <div class="${plural}-archive">
    <h1>${pluralCapitalized}</h1>

    <div v-if="pending" class="loading">
      Loading ${plural}...
    </div>

    <div v-else-if="error" class="error">
      Error loading ${plural}: {{ error.message }}
    </div>

${templateContent[displayStyle]}

    <p v-else>No ${plural} found.</p>
  </div>
</template>

<style scoped>
.${plural}-archive {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.loading, .error {
  padding: 2rem;
  text-align: center;
}

.error {
  color: #c00;
}
${styleContent[displayStyle]}
</style>
`

  // Determine route/filename
  const route = customRoute
    ? customRoute.replace(/^\//, '').replace(/\/$/, '')
    : (ct.name === 'post' ? 'blog' : plural)

  return {
    filename: `pages/${route}/index.vue`,
    content
  }
}

function generateSinglePage(ct: ContentType, customRoute?: string): { filename: string, content: string } {
  const singular = ct.graphqlSingleName
  const singularCapitalized = singular.charAt(0).toUpperCase() + singular.slice(1)
  const plural = ct.graphqlPluralName

  const content = `<script setup lang="ts">
/**
 * Single ${singularCapitalized} Page
 * Generated by WPNuxt MCP
 */
const route = useRoute()

// Variables must be reactive (computed) for client-side navigation to refetch
const { data: ${singular}, pending, error } = await use${singularCapitalized}BySlug(
  computed(() => ({ slug: route.params.slug as string }))
)

// SEO
useSeoMeta({
  title: () => ${singular}.value?.title || '${singularCapitalized}',
  description: () => ${singular}.value?.excerpt?.replace(/<[^>]*>/g, '').slice(0, 160) || ''
})
</script>

<template>
  <article class="${singular}-single">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="${singular}">
      <header class="${singular}-header">
        <h1>{{ ${singular}.title }}</h1>
        <time v-if="${singular}.date" :datetime="${singular}.date">
          {{ new Date(${singular}.date).toLocaleDateString() }}
        </time>
      </header>

      <img
        v-if="${singular}.featuredImage"
        :src="${singular}.featuredImage.node.sourceUrl"
        :alt="${singular}.featuredImage.node.altText || ${singular}.title"
        class="featured-image"
      />

      <div
        v-if="${singular}.content"
        class="${singular}-content"
        v-html="${singular}.content"
      />
    </template>
  </article>
</template>

<style scoped>
.${singular}-single {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

.${singular}-header {
  margin-bottom: 2rem;
}

.${singular}-header h1 {
  margin: 0 0 0.5rem;
}

.${singular}-header time {
  color: #666;
}

.featured-image {
  width: 100%;
  height: auto;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.${singular}-content {
  line-height: 1.8;
}

.${singular}-content :deep(img) {
  max-width: 100%;
  height: auto;
}
</style>
`

  return {
    filename: (() => {
      const route = customRoute
        ? customRoute.replace(/^\//, '').replace(/\/$/, '')
        : (ct.name === 'post' ? 'blog' : plural)
      return `pages/${route}/[slug].vue`
    })(),
    content
  }
}

function generateCatchAllPage(): { filename: string, content: string } {
  const content = `<script setup lang="ts">
/**
 * Catch-all Route
 * Handles WordPress pages and posts by URI
 * Generated by WPNuxt MCP
 */
const route = useRoute()

// Variables must be reactive (computed) for client-side navigation to refetch
const { data: node, pending, error } = await useNodeByUri(computed(() => ({ uri: route.path })))

// SEO
useSeoMeta({
  title: () => node.value?.title || 'Page',
  description: () => node.value?.excerpt?.replace(/<[^>]*>/g, '').slice(0, 160) || ''
})
</script>

<template>
  <article class="content-single">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="node">
      <header class="content-header">
        <h1>{{ node.title }}</h1>
        <p v-if="node.date" class="content-date">
          {{ new Date(node.date).toLocaleDateString() }}
        </p>
      </header>

      <img
        v-if="node.featuredImage"
        :src="node.featuredImage.node.sourceUrl"
        :alt="node.featuredImage.node.altText || node.title"
        class="featured-image"
      />

      <div
        v-if="node.content"
        class="content-body"
        v-html="node.content"
      />
    </template>
  </article>
</template>

<style scoped>
.content-single {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

.content-header {
  margin-bottom: 2rem;
}

.content-header h1 {
  margin: 0 0 0.5rem 0;
}

.content-date {
  color: #666;
  margin: 0;
}

.featured-image {
  width: 100%;
  height: auto;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.content-body {
  line-height: 1.8;
}

.content-body :deep(img) {
  max-width: 100%;
  height: auto;
}
</style>
`

  return {
    filename: 'pages/[...slug].vue',
    content
  }
}

function generateHomePage(settings: SiteSettings): { filename: string, content: string } {
  const isStaticFront = settings.readingSettings.showOnFront === 'page'

  const content = isStaticFront
    ? `<script setup lang="ts">
/**
 * Home Page (Static Front Page)
 * WordPress is configured to show a specific page as the front page
 * Generated by WPNuxt MCP
 */

// Fetch the front page
const { data: page, pending, error } = await useLazyPageByUri({
  uri: '/'
})

useSeoMeta({
  title: () => page.value?.title || 'Home'
})
</script>

<template>
  <div class="home-page">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="page">
      <h1>{{ page.title }}</h1>
      <div v-if="page.content" v-html="page.content" />
    </template>
  </div>
</template>

<style scoped>
.home-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}
</style>
`
    : `<script setup lang="ts">
/**
 * Home Page (Blog Posts)
 * WordPress is configured to show latest posts on the front page
 * Generated by WPNuxt MCP
 */

// Fetch latest posts
const { data: posts, pending, error } = await useLazyPosts({
  first: 10
})

useSeoMeta({
  title: 'Home'
})
</script>

<template>
  <div class="home-page">
    <h1>Latest Posts</h1>

    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <div v-else-if="posts" class="posts-list">
      <article v-for="post in posts" :key="post.id" class="post-card">
        <NuxtLink :to="post.uri">
          <img
            v-if="post.featuredImage"
            :src="post.featuredImage.node.sourceUrl"
            :alt="post.featuredImage.node.altText || post.title"
          />
          <h2>{{ post.title }}</h2>
          <p v-if="post.excerpt" v-html="post.excerpt" />
        </NuxtLink>
      </article>
    </div>

    <p v-else>No posts found.</p>
  </div>
</template>

<style scoped>
.home-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.posts-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 2rem;
}

.post-card {
  border: 1px solid #eee;
  border-radius: 8px;
  overflow: hidden;
}

.post-card img {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.post-card h2 {
  padding: 1rem;
  margin: 0;
}

.post-card p {
  padding: 0 1rem 1rem;
  margin: 0;
  color: #666;
}
</style>
`

  return {
    filename: 'pages/index.vue',
    content
  }
}

// Built-in content types - we don't generate pages for these (except post/page)
const BUILTIN_SKIP_TYPES = ['attachment', 'nav_menu_item', 'revision']

export default defineMcpTool({
  description: `Generate Nuxt page components for WordPress content types. Creates index (archive) and single pages with proper data fetching.

By default, generates pages for posts, pages, AND all custom post types found in WordPress.

When generating pages for custom post types, you can specify display preferences:
- displayStyle: 'grid' (cards in a grid), 'list' (simple list), or 'detailed' (list with images and excerpts)
- customRoute: override the default route (e.g., '/shop' instead of '/products')`,
  inputSchema: {
    contentTypes: z.array(z.string()).optional().describe('Specific content types to generate pages for. If not specified, generates for post, page, and all custom post types.'),
    includeHome: z.boolean().optional().describe('Generate home page based on WordPress reading settings (default: true)'),
    includeCatchAll: z.boolean().optional().describe('Generate catch-all route for WordPress pages and posts using NodeByUri (default: true)'),
    includeCustomPostTypes: z.boolean().optional().describe('Include all custom post types automatically (default: true)'),
    displayPreferences: z.array(z.object({
      contentType: z.string().describe('Content type name (e.g., "product", "event")'),
      displayStyle: z.enum(['grid', 'list', 'detailed']).optional().describe('How to display items: grid (cards), list (simple), or detailed (with images)'),
      customRoute: z.string().optional().describe('Custom route path (e.g., "/shop" instead of "/products")')
    })).optional().describe('Display preferences for each content type')
  },
  async handler({ contentTypes: filterContentTypes, includeHome = true, includeCatchAll = true, includeCustomPostTypes = true, displayPreferences = [] }) {
    // Fetch content types and settings
    const [ctResult, settingsResult] = await Promise.all([
      executeGraphQL<{ contentTypes: { nodes: ContentType[] } }>(CONTENT_TYPES_QUERY),
      executeGraphQL<SiteSettings>(SITE_SETTINGS_QUERY)
    ])

    if (ctResult.errors) {
      return textResult(`GraphQL Error: ${ctResult.errors.map(e => e.message).join(', ')}`)
    }

    const allContentTypes = ctResult.data?.contentTypes.nodes ?? []
    const settings = settingsResult.data

    // Determine which content types to generate pages for
    let contentTypesToGenerate: ContentType[]

    if (filterContentTypes && filterContentTypes.length > 0) {
      // Use explicitly specified content types
      contentTypesToGenerate = allContentTypes.filter(ct =>
        filterContentTypes.includes(ct.name) || filterContentTypes.includes(ct.graphqlSingleName)
      )
    } else if (includeCustomPostTypes) {
      // Include post, page, and all custom post types (exclude built-in skip types)
      contentTypesToGenerate = allContentTypes.filter(ct =>
        !BUILTIN_SKIP_TYPES.includes(ct.name)
      )
    } else {
      // Only post and page
      contentTypesToGenerate = allContentTypes.filter(ct =>
        ct.name === 'post' || ct.name === 'page'
      )
    }

    const generatedPages: Array<{ filename: string, content: string, description: string }> = []

    // Generate home page
    if (includeHome && settings) {
      const homePage = generateHomePage(settings)
      generatedPages.push({
        ...homePage,
        description: settings.readingSettings.showOnFront === 'page'
          ? 'Static front page (WordPress configured to show a page)'
          : 'Blog home page (WordPress configured to show latest posts)'
      })
    }

    // Generate pages for each content type
    for (const ct of contentTypesToGenerate) {
      // Skip pages - they're handled by catch-all route
      if (ct.name === 'page' && includeCatchAll) {
        continue
      }

      // Skip posts if:
      // 1. The homepage already shows posts (showOnFront === 'posts')
      // 2. And we have a catch-all route that can handle individual posts
      // This avoids redundant /blog section when homepage is the blog
      if (ct.name === 'post' && includeCatchAll) {
        const showPostsOnHome = settings?.readingSettings.showOnFront === 'posts'
        if (showPostsOnHome) {
          // Homepage shows posts, catch-all handles individual posts - skip /blog
          continue
        }
      }

      // Get display preferences for this content type
      const pref = displayPreferences.find(p =>
        p.contentType === ct.name || p.contentType === ct.graphqlSingleName
      )

      // Archive/list page
      const listPage = generateListPage(ct, pref?.displayStyle || 'grid', pref?.customRoute)
      generatedPages.push({
        ...listPage,
        description: `Archive page for ${ct.graphqlPluralName}${pref?.displayStyle ? ` (${pref.displayStyle} layout)` : ''}`
      })

      // Single page
      const singlePage = generateSinglePage(ct, pref?.customRoute)
      generatedPages.push({
        ...singlePage,
        description: `Single ${ct.graphqlSingleName} page`
      })
    }

    // Generate catch-all for pages and posts
    if (includeCatchAll) {
      const catchAllPage = generateCatchAllPage()
      generatedPages.push({
        ...catchAllPage,
        description: 'Catch-all route for WordPress pages and posts by URI'
      })
    }

    return jsonResult({
      summary: {
        totalPages: generatedPages.length,
        contentTypesIncluded: contentTypesToGenerate.map(ct => ct.name),
        wordpressSettings: settings
          ? {
              showOnFront: settings.readingSettings.showOnFront,
              hasStaticFrontPage: settings.readingSettings.showOnFront === 'page'
            }
          : null
      },
      instructions: [
        'Create these files in your Nuxt project (in app/pages/)',
        'Make sure you have the corresponding GraphQL queries in app/extend/queries/',
        'Run `pnpm run dev:prepare` to generate composables before using the pages'
      ],
      pages: generatedPages.map(p => ({
        filename: p.filename,
        description: p.description
      })),
      generatedCode: generatedPages.map(p =>
        `// ${p.filename}\n// ${p.description}\n\n${p.content}`
      ).join('\n\n// ===================================\n\n')
    })
  }
})
