import { z } from 'zod'
import { executeGraphQL, CONTENT_TYPES_QUERY, SITE_SETTINGS_QUERY } from '../../utils/graphql'

interface ContentType {
  name: string
  graphqlSingleName: string
  graphqlPluralName: string
  hierarchical: boolean
  hasArchive: boolean | null
}

interface SiteSettings {
  readingSettings: {
    showOnFront: string
    pageOnFront: number
    pageForPosts: number
  }
}

function generateListPage(ct: ContentType): { filename: string, content: string } {
  const plural = ct.graphqlPluralName
  const singular = ct.graphqlSingleName
  const pluralCapitalized = plural.charAt(0).toUpperCase() + plural.slice(1)

  const content = `<script setup lang="ts">
/**
 * ${pluralCapitalized} Archive Page
 * Generated by WPNuxt MCP
 */

// Fetch ${plural} with pagination
const { data: ${plural}, pending, error } = await useLazy${pluralCapitalized}({
  first: 10
})

// SEO
useSeoMeta({
  title: '${pluralCapitalized}',
  description: 'Browse all ${plural}'
})
</script>

<template>
  <div class="${plural}-archive">
    <h1>${pluralCapitalized}</h1>

    <div v-if="pending" class="loading">
      Loading ${plural}...
    </div>

    <div v-else-if="error" class="error">
      Error loading ${plural}: {{ error.message }}
    </div>

    <div v-else-if="${plural}" class="${plural}-list">
      <article
        v-for="${singular} in ${plural}"
        :key="${singular}.id"
        class="${singular}-card"
      >
        <NuxtLink :to="${singular}.uri">
          <img
            v-if="${singular}.featuredImage"
            :src="${singular}.featuredImage.node.sourceUrl"
            :alt="${singular}.featuredImage.node.altText || ${singular}.title"
          />
          <h2>{{ ${singular}.title }}</h2>
          <p v-if="${singular}.excerpt" v-html="${singular}.excerpt" />
        </NuxtLink>
      </article>
    </div>

    <p v-else>No ${plural} found.</p>
  </div>
</template>

<style scoped>
.${plural}-archive {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.${plural}-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 2rem;
}

.${singular}-card {
  border: 1px solid #eee;
  border-radius: 8px;
  overflow: hidden;
}

.${singular}-card img {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.${singular}-card h2 {
  padding: 1rem;
  margin: 0;
}

.${singular}-card p {
  padding: 0 1rem 1rem;
  margin: 0;
  color: #666;
}
</style>
`

  return {
    filename: ct.name === 'post' ? 'pages/blog/index.vue' : `pages/${plural}/index.vue`,
    content
  }
}

function generateSinglePage(ct: ContentType): { filename: string, content: string } {
  const singular = ct.graphqlSingleName
  const singularCapitalized = singular.charAt(0).toUpperCase() + singular.slice(1)

  const content = `<script setup lang="ts">
/**
 * Single ${singularCapitalized} Page
 * Generated by WPNuxt MCP
 */
const route = useRoute()
const slug = route.params.slug as string

// Fetch single ${singular}
const { data: ${singular}, pending, error } = await useLazy${singularCapitalized}BySlug({
  slug
})

// Handle 404
if (!${singular}.value && !pending.value) {
  throw createError({
    statusCode: 404,
    statusMessage: '${singularCapitalized} not found'
  })
}

// SEO
useSeoMeta({
  title: () => ${singular}.value?.title || '${singularCapitalized}',
  description: () => ${singular}.value?.excerpt?.replace(/<[^>]*>/g, '').slice(0, 160) || ''
})
</script>

<template>
  <article class="${singular}-single">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="${singular}">
      <header class="${singular}-header">
        <h1>{{ ${singular}.title }}</h1>
        <time v-if="${singular}.date" :datetime="${singular}.date">
          {{ new Date(${singular}.date).toLocaleDateString() }}
        </time>
      </header>

      <img
        v-if="${singular}.featuredImage"
        :src="${singular}.featuredImage.node.sourceUrl"
        :alt="${singular}.featuredImage.node.altText || ${singular}.title"
        class="featured-image"
      />

      <div
        v-if="${singular}.content"
        class="${singular}-content"
        v-html="${singular}.content"
      />
    </template>
  </article>
</template>

<style scoped>
.${singular}-single {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

.${singular}-header {
  margin-bottom: 2rem;
}

.${singular}-header h1 {
  margin: 0 0 0.5rem;
}

.${singular}-header time {
  color: #666;
}

.featured-image {
  width: 100%;
  height: auto;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.${singular}-content {
  line-height: 1.8;
}

.${singular}-content :deep(img) {
  max-width: 100%;
  height: auto;
}
</style>
`

  return {
    filename: ct.name === 'post' ? 'pages/blog/[slug].vue' : `pages/${ct.graphqlPluralName}/[slug].vue`,
    content
  }
}

function generateCatchAllPage(): { filename: string, content: string } {
  const content = `<script setup lang="ts">
/**
 * Catch-all Page Route
 * Handles WordPress pages with nested slugs (e.g., /about/team)
 * Generated by WPNuxt MCP
 */
const route = useRoute()
const uri = '/' + (Array.isArray(route.params.slug) ? route.params.slug.join('/') : route.params.slug) + '/'

// Fetch page by URI
const { data: page, pending, error } = await useLazyPageByUri({
  uri
})

// Handle 404
if (!page.value && !pending.value) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Page not found'
  })
}

// SEO
useSeoMeta({
  title: () => page.value?.title || 'Page',
  description: () => page.value?.excerpt?.replace(/<[^>]*>/g, '').slice(0, 160) || ''
})
</script>

<template>
  <article class="page-single">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="page">
      <header class="page-header">
        <h1>{{ page.title }}</h1>
      </header>

      <img
        v-if="page.featuredImage"
        :src="page.featuredImage.node.sourceUrl"
        :alt="page.featuredImage.node.altText || page.title"
        class="featured-image"
      />

      <div
        v-if="page.content"
        class="page-content"
        v-html="page.content"
      />
    </template>
  </article>
</template>

<style scoped>
.page-single {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

.page-header {
  margin-bottom: 2rem;
}

.page-header h1 {
  margin: 0;
}

.featured-image {
  width: 100%;
  height: auto;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.page-content {
  line-height: 1.8;
}

.page-content :deep(img) {
  max-width: 100%;
  height: auto;
}
</style>
`

  return {
    filename: 'pages/[...slug].vue',
    content
  }
}

function generateHomePage(settings: SiteSettings): { filename: string, content: string } {
  const isStaticFront = settings.readingSettings.showOnFront === 'page'

  const content = isStaticFront
    ? `<script setup lang="ts">
/**
 * Home Page (Static Front Page)
 * WordPress is configured to show a specific page as the front page
 * Generated by WPNuxt MCP
 */

// Fetch the front page
const { data: page, pending, error } = await useLazyPageByUri({
  uri: '/'
})

useSeoMeta({
  title: () => page.value?.title || 'Home'
})
</script>

<template>
  <div class="home-page">
    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <template v-else-if="page">
      <h1>{{ page.title }}</h1>
      <div v-if="page.content" v-html="page.content" />
    </template>
  </div>
</template>

<style scoped>
.home-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}
</style>
`
    : `<script setup lang="ts">
/**
 * Home Page (Blog Posts)
 * WordPress is configured to show latest posts on the front page
 * Generated by WPNuxt MCP
 */

// Fetch latest posts
const { data: posts, pending, error } = await useLazyPosts({
  first: 10
})

useSeoMeta({
  title: 'Home'
})
</script>

<template>
  <div class="home-page">
    <h1>Latest Posts</h1>

    <div v-if="pending" class="loading">
      Loading...
    </div>

    <div v-else-if="error" class="error">
      Error: {{ error.message }}
    </div>

    <div v-else-if="posts" class="posts-list">
      <article v-for="post in posts" :key="post.id" class="post-card">
        <NuxtLink :to="post.uri">
          <img
            v-if="post.featuredImage"
            :src="post.featuredImage.node.sourceUrl"
            :alt="post.featuredImage.node.altText || post.title"
          />
          <h2>{{ post.title }}</h2>
          <p v-if="post.excerpt" v-html="post.excerpt" />
        </NuxtLink>
      </article>
    </div>

    <p v-else>No posts found.</p>
  </div>
</template>

<style scoped>
.home-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.posts-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 2rem;
}

.post-card {
  border: 1px solid #eee;
  border-radius: 8px;
  overflow: hidden;
}

.post-card img {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.post-card h2 {
  padding: 1rem;
  margin: 0;
}

.post-card p {
  padding: 0 1rem 1rem;
  margin: 0;
  color: #666;
}
</style>
`

  return {
    filename: 'pages/index.vue',
    content
  }
}

export default defineMcpTool({
  description: 'Generate Nuxt page components for WordPress content types. Creates index (archive) and single pages with proper data fetching.',
  inputSchema: {
    contentTypes: z.array(z.string()).optional().describe('Specific content types to generate pages for (default: post, page)'),
    includeHome: z.boolean().optional().describe('Generate home page based on WordPress reading settings (default: true)'),
    includeCatchAll: z.boolean().optional().describe('Generate catch-all route for WordPress pages (default: true)')
  },
  async handler({ contentTypes: filterContentTypes, includeHome = true, includeCatchAll = true }) {
    // Fetch content types and settings
    const [ctResult, settingsResult] = await Promise.all([
      executeGraphQL<{ contentTypes: { nodes: ContentType[] } }>(CONTENT_TYPES_QUERY),
      executeGraphQL<SiteSettings>(SITE_SETTINGS_QUERY)
    ])

    if (ctResult.errors) {
      return textResult(`GraphQL Error: ${ctResult.errors.map(e => e.message).join(', ')}`)
    }

    const allContentTypes = ctResult.data?.contentTypes.nodes ?? []
    const settings = settingsResult.data

    // Filter to post and page by default, or use specified content types
    let contentTypesToGenerate = allContentTypes.filter(ct =>
      ct.name === 'post' || ct.name === 'page'
    )

    if (filterContentTypes && filterContentTypes.length > 0) {
      contentTypesToGenerate = allContentTypes.filter(ct =>
        filterContentTypes.includes(ct.name) || filterContentTypes.includes(ct.graphqlSingleName)
      )
    }

    const generatedPages: Array<{ filename: string, content: string, description: string }> = []

    // Generate home page
    if (includeHome && settings) {
      const homePage = generateHomePage(settings)
      generatedPages.push({
        ...homePage,
        description: settings.readingSettings.showOnFront === 'page'
          ? 'Static front page (WordPress configured to show a page)'
          : 'Blog home page (WordPress configured to show latest posts)'
      })
    }

    // Generate pages for each content type
    for (const ct of contentTypesToGenerate) {
      // Skip pages for catch-all route
      if (ct.name === 'page' && includeCatchAll) {
        continue
      }

      // Archive/list page
      const listPage = generateListPage(ct)
      generatedPages.push({
        ...listPage,
        description: `Archive page for ${ct.graphqlPluralName}`
      })

      // Single page
      const singlePage = generateSinglePage(ct)
      generatedPages.push({
        ...singlePage,
        description: `Single ${ct.graphqlSingleName} page`
      })
    }

    // Generate catch-all for pages
    if (includeCatchAll) {
      const catchAllPage = generateCatchAllPage()
      generatedPages.push({
        ...catchAllPage,
        description: 'Catch-all route for WordPress pages with nested slugs'
      })
    }

    return jsonResult({
      summary: {
        totalPages: generatedPages.length,
        contentTypesIncluded: contentTypesToGenerate.map(ct => ct.name),
        wordpressSettings: settings
          ? {
              showOnFront: settings.readingSettings.showOnFront,
              hasStaticFrontPage: settings.readingSettings.showOnFront === 'page'
            }
          : null
      },
      instructions: [
        'Create these files in your Nuxt project',
        'Make sure you have the corresponding GraphQL queries in extend/queries/',
        'Run `pnpm run dev:prepare` to generate composables before using the pages'
      ],
      pages: generatedPages.map(p => ({
        filename: p.filename,
        description: p.description
      })),
      generatedCode: generatedPages.map(p =>
        `// ${p.filename}\n// ${p.description}\n\n${p.content}`
      ).join('\n\n// ===================================\n\n')
    })
  }
})
