import { z } from 'zod'
import { executeGraphQL, MENUS_QUERY } from '../../utils/graphql'

interface MenuItem {
  id: string
  label: string
  url: string
  path: string
  parentId?: string
  cssClasses?: string[]
  target?: string
  childItems?: {
    nodes: MenuItem[]
  }
}

interface Menu {
  id: string
  name: string
  slug: string
  locations: string[]
  menuItems: {
    nodes: MenuItem[]
  }
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('')
}

function generateMenuQuery(): { filename: string, content: string } {
  const content = `# Menu Queries
# Generated by WPNuxt MCP
# Place in: extend/queries/Menus.gql

query Menus {
  menus {
    nodes {
      id
      databaseId
      name
      slug
      locations
      menuItems(first: 100) {
        nodes {
          id
          parentId
          label
          url
          path
          target
          cssClasses
          childItems {
            nodes {
              id
              parentId
              label
              url
              path
              target
              cssClasses
            }
          }
        }
      }
    }
  }
}

query MenuByLocation($location: MenuLocationEnum!) {
  menuItems(where: { location: $location }, first: 100) {
    nodes {
      id
      parentId
      label
      url
      path
      target
      cssClasses
      childItems {
        nodes {
          id
          parentId
          label
          url
          path
          target
          cssClasses
        }
      }
    }
  }
}

query MenuBySlug($slug: ID!) {
  menu(id: $slug, idType: SLUG) {
    id
    name
    slug
    menuItems(first: 100) {
      nodes {
        id
        parentId
        label
        url
        path
        target
        cssClasses
        childItems {
          nodes {
            id
            parentId
            label
            url
            path
            target
            cssClasses
          }
        }
      }
    }
  }
}
`

  return {
    filename: 'extend/queries/Menus.gql',
    content
  }
}

function generateMenuItemComponent(): { filename: string, content: string } {
  const content = `<script setup lang="ts">
/**
 * Menu Item Component
 * Renders a single menu item with optional children
 * Generated by WPNuxt MCP
 */

interface MenuItem {
  id: string
  label: string
  url: string
  path: string
  target?: string
  cssClasses?: string[]
  childItems?: {
    nodes: MenuItem[]
  }
}

interface Props {
  item: MenuItem
  depth?: number
}

const props = withDefaults(defineProps<Props>(), {
  depth: 0
})

const hasChildren = computed(() =>
  props.item.childItems?.nodes && props.item.childItems.nodes.length > 0
)

// Convert WordPress URL to internal path if same domain
const linkPath = computed(() => {
  if (props.item.path) {
    return props.item.path
  }
  try {
    const url = new URL(props.item.url)
    // If it's a relative URL or same domain, use path
    return url.pathname
  } catch {
    return props.item.url
  }
})

const isExternal = computed(() => {
  return props.item.target === '_blank' || props.item.url.startsWith('http')
})
</script>

<template>
  <li
    class="menu-item"
    :class="[
      \`depth-\${depth}\`,
      { 'has-children': hasChildren },
      ...(item.cssClasses || [])
    ]"
  >
    <NuxtLink
      v-if="!isExternal"
      :to="linkPath"
      class="menu-link"
    >
      {{ item.label }}
    </NuxtLink>
    <a
      v-else
      :href="item.url"
      :target="item.target"
      :rel="item.target === '_blank' ? 'noopener noreferrer' : undefined"
      class="menu-link"
    >
      {{ item.label }}
    </a>

    <ul v-if="hasChildren" class="submenu">
      <MenuItem
        v-for="child in item.childItems?.nodes"
        :key="child.id"
        :item="child"
        :depth="depth + 1"
      />
    </ul>
  </li>
</template>

<style scoped>
.menu-item {
  position: relative;
  list-style: none;
}

.menu-link {
  display: block;
  padding: 0.5rem 1rem;
  text-decoration: none;
  color: inherit;
  transition: color 0.2s, background-color 0.2s;
}

.menu-link:hover {
  color: var(--menu-hover-color, #0066cc);
}

.submenu {
  display: none;
  position: absolute;
  top: 100%;
  left: 0;
  min-width: 200px;
  padding: 0;
  margin: 0;
  background: white;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  border-radius: 4px;
  z-index: 100;
}

.menu-item.has-children:hover > .submenu {
  display: block;
}

.submenu .submenu {
  top: 0;
  left: 100%;
}

.depth-1 .menu-link,
.depth-2 .menu-link {
  padding: 0.75rem 1rem;
}

.depth-1 .menu-link:hover,
.depth-2 .menu-link:hover {
  background-color: #f5f5f5;
}
</style>
`

  return {
    filename: 'components/menu/MenuItem.vue',
    content
  }
}

function generateNavComponent(menu: Menu, variant: 'header' | 'footer' | 'mobile'): { filename: string, content: string } {
  const menuName = toPascalCase(menu.name)
  const menuSlug = menu.slug
  const componentName = `${menuName}${toPascalCase(variant)}Nav`

  const variants: Record<string, string> = {
    header: `<script setup lang="ts">
/**
 * ${menu.name} Header Navigation
 * Generated by WPNuxt MCP
 */

interface MenuItem {
  id: string
  label: string
  url: string
  path: string
  target?: string
  cssClasses?: string[]
  childItems?: {
    nodes: MenuItem[]
  }
}

// Fetch menu by slug
const { data: menuData } = await useLazyMenuBySlug({
  slug: '${menuSlug}'
})

const menuItems = computed(() =>
  menuData.value?.menuItems?.nodes?.filter(item => !item.parentId) || []
)
</script>

<template>
  <nav class="header-nav" aria-label="${menu.name}">
    <ul class="nav-menu">
      <MenuItem
        v-for="item in menuItems"
        :key="item.id"
        :item="item"
      />
    </ul>
  </nav>
</template>

<style scoped>
.header-nav {
  display: flex;
  align-items: center;
}

.nav-menu {
  display: flex;
  gap: 0.5rem;
  padding: 0;
  margin: 0;
  list-style: none;
}

@media (max-width: 768px) {
  .header-nav {
    display: none;
  }
}
</style>
`,

    footer: `<script setup lang="ts">
/**
 * ${menu.name} Footer Navigation
 * Generated by WPNuxt MCP
 */

interface MenuItem {
  id: string
  label: string
  url: string
  path: string
  target?: string
  cssClasses?: string[]
}

// Fetch menu by slug
const { data: menuData } = await useLazyMenuBySlug({
  slug: '${menuSlug}'
})

const menuItems = computed(() =>
  menuData.value?.menuItems?.nodes?.filter(item => !item.parentId) || []
)
</script>

<template>
  <nav class="footer-nav" aria-label="${menu.name}">
    <ul class="nav-menu">
      <li v-for="item in menuItems" :key="item.id" class="nav-item">
        <NuxtLink :to="item.path || item.url" class="nav-link">
          {{ item.label }}
        </NuxtLink>
      </li>
    </ul>
  </nav>
</template>

<style scoped>
.footer-nav {
  padding: 1rem 0;
}

.nav-menu {
  display: flex;
  flex-wrap: wrap;
  gap: 1.5rem;
  padding: 0;
  margin: 0;
  list-style: none;
}

.nav-link {
  color: #666;
  text-decoration: none;
  font-size: 0.875rem;
  transition: color 0.2s;
}

.nav-link:hover {
  color: #333;
}

@media (max-width: 768px) {
  .nav-menu {
    flex-direction: column;
    gap: 0.75rem;
    text-align: center;
  }
}
</style>
`,

    mobile: `<script setup lang="ts">
/**
 * ${menu.name} Mobile Navigation
 * Generated by WPNuxt MCP
 */

interface MenuItem {
  id: string
  label: string
  url: string
  path: string
  target?: string
  cssClasses?: string[]
  childItems?: {
    nodes: MenuItem[]
  }
}

interface Props {
  isOpen?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  isOpen: false
})

const emit = defineEmits<{
  close: []
}>()

// Fetch menu by slug
const { data: menuData } = await useLazyMenuBySlug({
  slug: '${menuSlug}'
})

const menuItems = computed(() =>
  menuData.value?.menuItems?.nodes?.filter(item => !item.parentId) || []
)

// Track expanded items
const expandedItems = ref<Set<string>>(new Set())

function toggleExpanded(id: string) {
  if (expandedItems.value.has(id)) {
    expandedItems.value.delete(id)
  } else {
    expandedItems.value.add(id)
  }
}

function handleLinkClick() {
  emit('close')
}
</script>

<template>
  <Transition name="slide">
    <nav v-if="isOpen" class="mobile-nav" aria-label="${menu.name}">
      <div class="mobile-nav-header">
        <button class="close-button" @click="emit('close')" aria-label="Close menu">
          ✕
        </button>
      </div>

      <ul class="mobile-menu">
        <li v-for="item in menuItems" :key="item.id" class="mobile-menu-item">
          <div class="menu-item-row">
            <NuxtLink
              :to="item.path || item.url"
              class="mobile-link"
              @click="handleLinkClick"
            >
              {{ item.label }}
            </NuxtLink>
            <button
              v-if="item.childItems?.nodes?.length"
              class="expand-button"
              :aria-expanded="expandedItems.has(item.id)"
              @click="toggleExpanded(item.id)"
            >
              <span :class="{ rotated: expandedItems.has(item.id) }">▼</span>
            </button>
          </div>

          <Transition name="expand">
            <ul
              v-if="item.childItems?.nodes?.length && expandedItems.has(item.id)"
              class="mobile-submenu"
            >
              <li v-for="child in item.childItems.nodes" :key="child.id">
                <NuxtLink
                  :to="child.path || child.url"
                  class="mobile-link submenu-link"
                  @click="handleLinkClick"
                >
                  {{ child.label }}
                </NuxtLink>
              </li>
            </ul>
          </Transition>
        </li>
      </ul>
    </nav>
  </Transition>
</template>

<style scoped>
.mobile-nav {
  position: fixed;
  inset: 0;
  background: white;
  z-index: 1000;
  overflow-y: auto;
}

.mobile-nav-header {
  display: flex;
  justify-content: flex-end;
  padding: 1rem;
  border-bottom: 1px solid #eee;
}

.close-button {
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0.5rem;
}

.mobile-menu {
  padding: 1rem;
  margin: 0;
  list-style: none;
}

.mobile-menu-item {
  border-bottom: 1px solid #eee;
}

.menu-item-row {
  display: flex;
  align-items: center;
}

.mobile-link {
  flex: 1;
  display: block;
  padding: 1rem 0;
  text-decoration: none;
  color: #333;
  font-size: 1.125rem;
}

.expand-button {
  background: none;
  border: none;
  padding: 1rem;
  cursor: pointer;
  font-size: 0.75rem;
  color: #666;
}

.expand-button span {
  display: inline-block;
  transition: transform 0.2s;
}

.expand-button span.rotated {
  transform: rotate(180deg);
}

.mobile-submenu {
  padding: 0 0 0.5rem 1rem;
  margin: 0;
  list-style: none;
}

.submenu-link {
  font-size: 1rem;
  color: #666;
  padding: 0.75rem 0;
}

/* Transitions */
.slide-enter-active,
.slide-leave-active {
  transition: transform 0.3s ease;
}

.slide-enter-from,
.slide-leave-to {
  transform: translateX(100%);
}

.expand-enter-active,
.expand-leave-active {
  transition: all 0.2s ease;
  overflow: hidden;
}

.expand-enter-from,
.expand-leave-to {
  opacity: 0;
  max-height: 0;
}

.expand-enter-to,
.expand-leave-from {
  max-height: 500px;
}
</style>
`
  }

  return {
    filename: `components/menu/${componentName}.vue`,
    content: variants[variant]
  }
}

function generateMenuToggleButton(): { filename: string, content: string } {
  const content = `<script setup lang="ts">
/**
 * Mobile Menu Toggle Button
 * Generated by WPNuxt MCP
 */

interface Props {
  isOpen?: boolean
}

defineProps<Props>()

const emit = defineEmits<{
  toggle: []
}>()
</script>

<template>
  <button
    class="menu-toggle"
    :aria-expanded="isOpen"
    aria-label="Toggle menu"
    @click="emit('toggle')"
  >
    <span class="hamburger" :class="{ open: isOpen }">
      <span class="line" />
      <span class="line" />
      <span class="line" />
    </span>
  </button>
</template>

<style scoped>
.menu-toggle {
  display: none;
  background: none;
  border: none;
  padding: 0.5rem;
  cursor: pointer;
}

@media (max-width: 768px) {
  .menu-toggle {
    display: block;
  }
}

.hamburger {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  width: 24px;
  height: 18px;
}

.line {
  display: block;
  width: 100%;
  height: 2px;
  background: #333;
  transition: all 0.3s ease;
}

.hamburger.open .line:nth-child(1) {
  transform: translateY(8px) rotate(45deg);
}

.hamburger.open .line:nth-child(2) {
  opacity: 0;
}

.hamburger.open .line:nth-child(3) {
  transform: translateY(-8px) rotate(-45deg);
}
</style>
`

  return {
    filename: 'components/menu/MenuToggle.vue',
    content
  }
}

export default defineMcpTool({
  description: 'Generate menu components from WordPress menus. Creates header, footer, and mobile navigation components with GraphQL queries.',
  inputSchema: {
    variants: z.array(z.enum(['header', 'footer', 'mobile'])).optional()
      .describe('Navigation variants to generate (default: all)'),
    includeQuery: z.boolean().optional()
      .describe('Include GraphQL menu queries (default: true)'),
    includeHelpers: z.boolean().optional()
      .describe('Include helper components like MenuItem and MenuToggle (default: true)')
  },
  async handler({ variants = ['header', 'footer', 'mobile'], includeQuery = true, includeHelpers = true }) {
    // Fetch menus from WordPress
    const result = await executeGraphQL<{ menus: { nodes: Menu[] } }>(MENUS_QUERY)

    if (result.errors) {
      return textResult(`GraphQL Error: ${result.errors.map(e => e.message).join(', ')}`)
    }

    const menus = result.data?.menus.nodes ?? []

    if (menus.length === 0) {
      return jsonResult({
        success: false,
        message: 'No menus found in WordPress. Create menus in WordPress Admin under Appearance > Menus.',
        components: []
      })
    }

    const generatedComponents: Array<{ filename: string, content: string, description: string }> = []

    // Generate query file
    if (includeQuery) {
      const menuQuery = generateMenuQuery()
      generatedComponents.push({
        ...menuQuery,
        description: 'GraphQL queries for fetching WordPress menus'
      })
    }

    // Generate helper components
    if (includeHelpers) {
      const menuItem = generateMenuItemComponent()
      generatedComponents.push({
        ...menuItem,
        description: 'Reusable menu item component with dropdown support'
      })

      const menuToggle = generateMenuToggleButton()
      generatedComponents.push({
        ...menuToggle,
        description: 'Mobile menu toggle button with hamburger animation'
      })
    }

    // Generate navigation components for each menu
    for (const menu of menus) {
      for (const variant of variants) {
        const navComponent = generateNavComponent(menu, variant)
        generatedComponents.push({
          ...navComponent,
          description: `${menu.name} ${variant} navigation (${menu.menuItems.nodes.length} items)`
        })
      }
    }

    return jsonResult({
      summary: {
        menusFound: menus.length,
        totalComponents: generatedComponents.length,
        variants: variants
      },
      menus: menus.map(m => ({
        name: m.name,
        slug: m.slug,
        locations: m.locations,
        itemCount: m.menuItems.nodes.length,
        topLevelItems: m.menuItems.nodes.filter(i => !i.parentId).length
      })),
      instructions: [
        'Create these files in your Nuxt project',
        'Add menu queries to extend/queries/ folder',
        'Run `pnpm run dev:prepare` to generate composables',
        'Import navigation components in your layout files'
      ],
      components: generatedComponents.map(c => ({
        filename: c.filename,
        description: c.description
      })),
      usage: {
        header: `<template>
  <header>
    <${toPascalCase(menus[0]?.name || 'Main')}HeaderNav />
    <MenuToggle :is-open="mobileMenuOpen" @toggle="mobileMenuOpen = !mobileMenuOpen" />
    <${toPascalCase(menus[0]?.name || 'Main')}MobileNav :is-open="mobileMenuOpen" @close="mobileMenuOpen = false" />
  </header>
</template>`,
        footer: `<template>
  <footer>
    <${toPascalCase(menus[0]?.name || 'Main')}FooterNav />
  </footer>
</template>`
      },
      generatedCode: generatedComponents.map(c =>
        `// ${c.filename}\n// ${c.description}\n\n${c.content}`
      ).join('\n\n// ===================================\n\n')
    })
  }
})
