import { z } from 'zod'
import { executeGraphQL, CONTENT_TYPES_QUERY, TAXONOMIES_QUERY } from '../../utils/graphql'

interface ContentType {
  name: string
  graphqlSingleName: string
  graphqlPluralName: string
  hierarchical: boolean
}

interface Taxonomy {
  name: string
  graphqlSingleName: string
  graphqlPluralName: string
}

function generateCardComponent(ct: ContentType): { filename: string, content: string } {
  const singular = ct.graphqlSingleName
  const singularCapitalized = singular.charAt(0).toUpperCase() + singular.slice(1)

  const content = `<script setup lang="ts">
/**
 * ${singularCapitalized} Card Component
 * Displays a preview card for a ${singular}
 * Generated by WPNuxt MCP
 */

interface Props {
  ${singular}: {
    id: string
    title: string
    uri: string
    excerpt?: string
    date?: string
    featuredImage?: {
      node: {
        sourceUrl: string
        altText?: string
      }
    }
    categories?: {
      nodes: Array<{ name: string; slug: string }>
    }
  }
}

defineProps<Props>()
</script>

<template>
  <article class="${singular}-card">
    <NuxtLink :to="${singular}.uri" class="card-link">
      <div v-if="${singular}.featuredImage" class="card-image">
        <img
          :src="${singular}.featuredImage.node.sourceUrl"
          :alt="${singular}.featuredImage.node.altText || ${singular}.title"
          loading="lazy"
        />
      </div>

      <div class="card-content">
        <div v-if="${singular}.categories?.nodes?.length" class="card-categories">
          <span
            v-for="category in ${singular}.categories.nodes"
            :key="category.slug"
            class="category-badge"
          >
            {{ category.name }}
          </span>
        </div>

        <h3 class="card-title">{{ ${singular}.title }}</h3>

        <p
          v-if="${singular}.excerpt"
          class="card-excerpt"
          v-html="${singular}.excerpt"
        />

        <time
          v-if="${singular}.date"
          :datetime="${singular}.date"
          class="card-date"
        >
          {{ new Date(${singular}.date).toLocaleDateString() }}
        </time>
      </div>
    </NuxtLink>
  </article>
</template>

<style scoped>
.${singular}-card {
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s, box-shadow 0.2s;
}

.${singular}-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
}

.card-link {
  display: block;
  text-decoration: none;
  color: inherit;
}

.card-image {
  aspect-ratio: 16 / 9;
  overflow: hidden;
}

.card-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.card-content {
  padding: 1rem;
}

.card-categories {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 0.5rem;
}

.category-badge {
  font-size: 0.75rem;
  padding: 0.25rem 0.5rem;
  background: #f0f0f0;
  border-radius: 4px;
  color: #666;
}

.card-title {
  margin: 0 0 0.5rem;
  font-size: 1.25rem;
  line-height: 1.3;
}

.card-excerpt {
  margin: 0 0 0.5rem;
  color: #666;
  font-size: 0.9rem;
  line-height: 1.5;
}

.card-excerpt :deep(p) {
  margin: 0;
}

.card-date {
  display: block;
  font-size: 0.8rem;
  color: #999;
}
</style>
`

  return {
    filename: `components/${singularCapitalized}Card.vue`,
    content
  }
}

function generateListComponent(ct: ContentType): { filename: string, content: string } {
  const singular = ct.graphqlSingleName
  const plural = ct.graphqlPluralName
  const singularCapitalized = singular.charAt(0).toUpperCase() + singular.slice(1)
  const pluralCapitalized = plural.charAt(0).toUpperCase() + plural.slice(1)

  const content = `<script setup lang="ts">
/**
 * ${pluralCapitalized} List Component
 * Displays a grid of ${singular} cards
 * Generated by WPNuxt MCP
 */

interface ${singularCapitalized} {
  id: string
  title: string
  uri: string
  excerpt?: string
  date?: string
  featuredImage?: {
    node: {
      sourceUrl: string
      altText?: string
    }
  }
  categories?: {
    nodes: Array<{ name: string; slug: string }>
  }
}

interface Props {
  ${plural}: ${singularCapitalized}[]
  columns?: 2 | 3 | 4
}

withDefaults(defineProps<Props>(), {
  columns: 3
})
</script>

<template>
  <div class="${plural}-list" :class="\`columns-\${columns}\`">
    <${singularCapitalized}Card
      v-for="${singular} in ${plural}"
      :key="${singular}.id"
      :${singular}="${singular}"
    />
  </div>
</template>

<style scoped>
.${plural}-list {
  display: grid;
  gap: 1.5rem;
}

.columns-2 {
  grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
}

.columns-3 {
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
}

.columns-4 {
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
}

@media (max-width: 768px) {
  .${plural}-list {
    grid-template-columns: 1fr;
  }
}
</style>
`

  return {
    filename: `components/${pluralCapitalized}List.vue`,
    content
  }
}

function generateTaxonomyListComponent(tax: Taxonomy): { filename: string, content: string } {
  const singular = tax.graphqlSingleName
  const plural = tax.graphqlPluralName
  const singularCapitalized = singular.charAt(0).toUpperCase() + singular.slice(1)
  const pluralCapitalized = plural.charAt(0).toUpperCase() + plural.slice(1)

  const content = `<script setup lang="ts">
/**
 * ${pluralCapitalized} List Component
 * Displays a list of ${plural} as badges or links
 * Generated by WPNuxt MCP
 */

interface ${singularCapitalized} {
  id: string
  name: string
  slug: string
  count?: number
}

interface Props {
  ${plural}: ${singularCapitalized}[]
  variant?: 'badges' | 'list' | 'inline'
  showCount?: boolean
  linkPrefix?: string
}

withDefaults(defineProps<Props>(), {
  variant: 'badges',
  showCount: false,
  linkPrefix: '/${plural}/'
})
</script>

<template>
  <div class="${plural}-list" :class="variant">
    <NuxtLink
      v-for="${singular} in ${plural}"
      :key="${singular}.id"
      :to="\`\${linkPrefix}\${${singular}.slug}\`"
      class="${singular}-item"
    >
      {{ ${singular}.name }}
      <span v-if="showCount && ${singular}.count" class="count">
        ({{ ${singular}.count }})
      </span>
    </NuxtLink>
  </div>
</template>

<style scoped>
.${plural}-list.badges {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.${plural}-list.badges .${singular}-item {
  display: inline-block;
  padding: 0.25rem 0.75rem;
  background: #f0f0f0;
  border-radius: 20px;
  font-size: 0.875rem;
  text-decoration: none;
  color: #333;
  transition: background 0.2s;
}

.${plural}-list.badges .${singular}-item:hover {
  background: #e0e0e0;
}

.${plural}-list.list {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.${plural}-list.list .${singular}-item {
  display: block;
  padding: 0.5rem 0;
  text-decoration: none;
  color: #333;
  border-bottom: 1px solid #eee;
}

.${plural}-list.list .${singular}-item:hover {
  color: #0066cc;
}

.${plural}-list.inline {
  display: inline;
}

.${plural}-list.inline .${singular}-item {
  text-decoration: none;
  color: #0066cc;
}

.${plural}-list.inline .${singular}-item:not(:last-child)::after {
  content: ', ';
  color: #333;
}

.count {
  color: #999;
  font-size: 0.8em;
}
</style>
`

  return {
    filename: `components/${pluralCapitalized}List.vue`,
    content
  }
}

function generateFeaturedImageComponent(): { filename: string, content: string } {
  const content = `<script setup lang="ts">
/**
 * Featured Image Component
 * Responsive image component with lazy loading and srcset support
 * Generated by WPNuxt MCP
 */

interface Props {
  image: {
    sourceUrl: string
    altText?: string
    mediaDetails?: {
      width: number
      height: number
    }
  }
  aspectRatio?: '16/9' | '4/3' | '1/1' | 'auto'
  rounded?: boolean
  priority?: boolean
}

withDefaults(defineProps<Props>(), {
  aspectRatio: 'auto',
  rounded: false,
  priority: false
})
</script>

<template>
  <div
    class="featured-image"
    :class="{ rounded }"
    :style="aspectRatio !== 'auto' ? { aspectRatio } : undefined"
  >
    <img
      :src="image.sourceUrl"
      :alt="image.altText || ''"
      :width="image.mediaDetails?.width"
      :height="image.mediaDetails?.height"
      :loading="priority ? 'eager' : 'lazy'"
    />
  </div>
</template>

<style scoped>
.featured-image {
  width: 100%;
  overflow: hidden;
}

.featured-image.rounded {
  border-radius: 8px;
}

.featured-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>
`

  return {
    filename: 'components/FeaturedImage.vue',
    content
  }
}

export default defineMcpTool({
  description: 'Generate Vue components for WordPress content types including cards, lists, and utility components.',
  inputSchema: {
    contentTypes: z.array(z.string()).optional().describe('Content types to generate components for (default: post, page)'),
    includeTaxonomies: z.boolean().optional().describe('Generate taxonomy list components (default: true)'),
    includeUtilities: z.boolean().optional().describe('Generate utility components like FeaturedImage (default: true)')
  },
  async handler({ contentTypes: filterContentTypes, includeTaxonomies = true, includeUtilities = true }) {
    const [ctResult, taxResult] = await Promise.all([
      executeGraphQL<{ contentTypes: { nodes: ContentType[] } }>(CONTENT_TYPES_QUERY),
      executeGraphQL<{ taxonomies: { nodes: Taxonomy[] } }>(TAXONOMIES_QUERY)
    ])

    if (ctResult.errors) {
      return textResult(`GraphQL Error: ${ctResult.errors.map(e => e.message).join(', ')}`)
    }

    const allContentTypes = ctResult.data?.contentTypes.nodes ?? []
    const allTaxonomies = taxResult.data?.taxonomies.nodes ?? []

    // Filter content types
    let contentTypesToGenerate = allContentTypes.filter(ct =>
      ct.name === 'post' || ct.name === 'page'
    )

    if (filterContentTypes && filterContentTypes.length > 0) {
      contentTypesToGenerate = allContentTypes.filter(ct =>
        filterContentTypes.includes(ct.name) || filterContentTypes.includes(ct.graphqlSingleName)
      )
    }

    const generatedComponents: Array<{ filename: string, content: string, description: string }> = []

    // Generate card and list components for each content type
    for (const ct of contentTypesToGenerate) {
      const cardComponent = generateCardComponent(ct)
      generatedComponents.push({
        ...cardComponent,
        description: `Card component for displaying ${ct.graphqlSingleName} preview`
      })

      const listComponent = generateListComponent(ct)
      generatedComponents.push({
        ...listComponent,
        description: `Grid list component for ${ct.graphqlPluralName}`
      })
    }

    // Generate taxonomy components
    if (includeTaxonomies) {
      for (const tax of allTaxonomies) {
        const taxComponent = generateTaxonomyListComponent(tax)
        generatedComponents.push({
          ...taxComponent,
          description: `List component for ${tax.graphqlPluralName}`
        })
      }
    }

    // Generate utility components
    if (includeUtilities) {
      const featuredImage = generateFeaturedImageComponent()
      generatedComponents.push({
        ...featuredImage,
        description: 'Responsive featured image component with lazy loading'
      })
    }

    return jsonResult({
      summary: {
        totalComponents: generatedComponents.length,
        contentTypeComponents: contentTypesToGenerate.length * 2,
        taxonomyComponents: includeTaxonomies ? allTaxonomies.length : 0,
        utilityComponents: includeUtilities ? 1 : 0
      },
      instructions: [
        'Create these files in your Nuxt project\'s components/ directory',
        'Components are auto-imported in Nuxt, no manual imports needed',
        'Customize styling to match your design system'
      ],
      components: generatedComponents.map(c => ({
        filename: c.filename,
        description: c.description
      })),
      generatedCode: generatedComponents.map(c =>
        `// ${c.filename}\n// ${c.description}\n\n${c.content}`
      ).join('\n\n// ===================================\n\n')
    })
  }
})
